### ISSUE TITLE
Remove Don! haha

### ISSUE THREAD

**Issue by dvetal** [industrydive/dive_sailthru_client#8]
Hi All,

Seems I am still in your REPO!!! Wrecking stuff! hahaha. no not really.  Can you please remove me?

Thanks,

Don Vetal

**Comment by lauralorenz** [comment]
hahaha hello! ok :P

**Comment by lauralorenz** [comment]
Actually @dvetal this repo is public and does not have you  explicitly listed as a collaborator on our settings side so I think this is related to some notification settings in your github account. Maybe check https://help.github.com/articles/managing-notifications-for-pushes-to-a-repository/?

Alternatively if what you got was a message from CircleCI, that might be because of some notification settings on your github account's link to CircleCI. I think that would be related to https://circleci.com/docs/1.0/faq/#how-can-i-delete-my-project

**Comment by elidickinson** [comment]
@dvetal pull requests accepted if you'd like to contribute :)
